# Generated by Django 5.1 on 2024-09-03 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_login_online', models.DateTimeField(null=True)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerBoosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boost_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part1.boost')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part1.player')),
            ],
        ),
    ]
